<?php
/**
 * @file
 * Rules export test module.
 */

/**
 * Defines the export of rule for testing import/export.
 */
function _rules_export_test_get_test_export() {
  return '{ "rules_export_test" : {
    "LABEL" : "Test import rule2",
    "PLUGIN" : "reaction rule",
    "WEIGHT" : "-1",
    "ACTIVE" : false,
    "OWNER" : "rules",
    "TAGS" : [ "bar", "baz", "foo" ],
    "REQUIRES" : [ "rules", "comment" ],
    "ON" : { "comment_insert" : [] },
    "IF" : [
      { "OR" : [
          { "NOT node_is_sticky" : { "node" : [ "comment:node" ] } },
          { "node_is_of_type" : {
              "node" : [ "comment:node" ],
              "type" : { "value" : { "page" : "page" } }
            }
          },
          { "NOT AND" : [ { "OR" : [] } ] }
        ]
      }
    ],
    "DO" : [
      { "data_set" : {
          "data" : [ "comment:node:created" ],
          "value" : { "select" : "site:current-date", "date_offset" : { "value" : -604800 } }
        }
      },
      { "node_make_sticky" : { "node" : [ "comment:node" ] } },
      { "variable_add" : {
          "USING" : { "type" : "token", "value" : "error" },
          "PROVIDE" : { "variable_added" : { "level" : "Error level" } }
        }
      },
      { "backdrop_message" : {
          "message" : "fein, [comment:node:title] has been made sticky!",
          "type" : [ "level" ]
        }
      },
      { "LOOP" : {
          "USING" : { "list" : [ "site:current-user:roles" ] },
          "ITEM" : { "current_role" : "Current role" },
          "DO" : [ { "backdrop_message" : { "message" : [ "current-role" ] } } ]
        }
      }
    ]
  }
}';
}
